plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0'  // or '3.4.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'home.exercise'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}





dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'org.postgresql:postgresql:42.7.1'
    //Akka
    implementation 'com.typesafe.akka:akka-actor-typed_2.13:2.8.5'
    implementation 'com.typesafe.akka:akka-stream_2.13:2.8.5'
    implementation 'com.typesafe.akka:akka-actor_2.13:2.8.5'
    implementation 'com.typesafe.akka:akka-slf4j_2.13:2.8.5'
    implementation 'com.typesafe.akka:akka-testkit_2.13:2.8.5'
    // implementation 'com.typesafe.akka:akka-discovery_2.13:2.8.5'
    // You might also need to explicitly add the gRPC runtime
    // implementation 'com.lightbend.akka.grpc:akka-grpc-runtime_2.13:2.8.5'
    
    // For Excel File Parsing
    implementation 'org.apache.poi:poi:5.2.4'
    implementation 'org.apache.poi:poi-ooxml:5.2.4'
    implementation('com.github.javafaker:javafaker:1.0.2') {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    // Database
    runtimeOnly 'org.postgresql:postgresql'
    
	 // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    
    // API Testing (REST Assured)
    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testImplementation 'io.rest-assured:json-path:5.5.0'
    testImplementation 'io.rest-assured:xml-path:5.5.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
